backend:
  name: github
  repo: GabrielRozendo/GabrielRozendo.github.io
  branch: main


media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "homelab"
    label: "Homelab"
    folder: "content/homelab"
    create: true
    fields:
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "now"
    label: "Now"
    folder: "content/now"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Root pages"
    files:

      - label: "About me (whoami)"
        name: "whoami"
        file: "content/whoami.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Show title", name: "showtitle", widget: "boolean", required: false }
          - { label: "Show date", name: "showdate", widget: "boolean", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Ideas"
        name: "ideas"
        file: "content/ideas/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "AI"
        name: "ai"
        file: "content/ai.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Me"
        name: "me"
        file: "content/me.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Show date", name: "showdate", widget: "boolean", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
